export const SHOWS_LOADING = 'SHOWS_LOADING';
export const SHOWS_FAILED = 'SHOWS_FAILED';
export const ADD_SHOWS = 'ADD_SHOWS';

export const SHOW_DETAILS_LOADING = 'SHOW_DETAILS_LOADING';
export const SHOW_DETAILS_FAILED = 'SHOW_DETAILS_FAILED';
export const ADD_SHOW_DETAILS = 'ADD_SHOW_DETAILS';
